### PR TITLE
Add support for Summer mode and hot water lock in buildSetBoilerStatusRequest

### PR DESCRIPTION
**Pull request by PxPert**
Hi,
I've slightly modified buildSetBoilerStatusRequest to add support for Summer Mode and Hot Water Lock as per OpenTherm function Matrix.
The default bool values are both false, so Backwards compatibility is preserved.

Thanks for your work supporting this library!

### CODE REVIEW

**Comment by FreeBear-nc** [comment]
Little bothered by your flag name.
The source uses enable[Flag], so to conform with convention, lockHotWater should be enableHotWaterBlocking. Aside from that, patch looks good.

**Comment by FreeBear-nc** [comment]
Generated a patch from your commit and massaged it to avoid any conflicts. Also changed lockHotWater to enableHotWaterBlocking.

(I still hate git).

**Comment by FreeBear-nc** [comment]
Closing pull request as patch has been applied manually.

**Comment by PxPert** [comment]
Thanks!

**Pull request closed without merging**
